# Generated by Django 2.1.7 on 2019-04-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pNo', models.CharField(max_length=20)),
                ('pBrand', models.CharField(max_length=20)),
                ('pPrice', models.CharField(max_length=20)),
                ('pContent', models.CharField(max_length=20)),
                ('pFile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weathers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wCity', models.CharField(max_length=20)),
                ('wDate', models.CharField(max_length=20)),
                ('wWeather', models.CharField(max_length=20)),
                ('wTemp', models.CharField(max_length=20)),
            ],
        ),
    ]
