# Generated by Django 2.1.7 on 2019-04-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190413_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='pNo',
            field=models.CharField(max_length=7),
        ),
    ]
