# Generated by Django 2.1.7 on 2019-04-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20190414_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='pNo',
            field=models.CharField(max_length=20),
        ),
    ]
