# Generated by Django 2.1.7 on 2019-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20190414_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='mid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
