# Generated by Django 2.1.7 on 2019-04-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_movies_mid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='mid',
            new_name='mId',
        ),
    ]
