# Generated by Django 2.1.7 on 2019-04-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_packaegs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packaegs',
            new_name='Packages',
        ),
    ]
