# Generated by Django 2.1.7 on 2019-04-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_auto_20190424_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='PTitle',
            new_name='pTitle',
        ),
    ]
